### ISSUE TITLE
Cross-post to Open Sea

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/sample-marketplace#104]
Bring back this functionality, but utilize the backend API for it (`execute/list` with orderbook=opensea)

Should be available for both List and Offer.

**Comment by rorygeoghegan** [comment]
Cross Post Offer
- [ ] Update Offer cross post copy to 'Post offer to OpenSea'
- [ ] Update disclaimer copy to '*OpenSea fee is taken out of the above amount if item is sold on OpenSea.'
- [ ] Move Post offer to OpenSea below the Expiration selection

Cross Post Listing
- [ ] Add support for cross post listing
- [ ] Add check box with 'Post listing to OpenSea' below expiration selection
- [ ] Only display OpenSea fee when box is checked
- [ ] When box is checked display disclaimer below You get amount - '*OpenSea fee is taken out of the above amount if item is sold on OpenSea.'
