### ISSUE TITLE
Update token page UI for ERC721 and ERC1155

### ISSUE THREAD

**Issue by rorygeoghegan** [reservoirprotocol/sample-marketplace#197]
- [x] Add token info section (including OS and Looksrare link, contract address that links to etherscan, token id and token standard)
- [x] Add collection info section
- [x] Move owner under Title for ERC721 tokens
- [ ] Add owners count and supply count on ERC1155 tokens
- [x] Add source name and icon to list price (clicks through to item on that marketplace)
- [x] Add token refresh button on all token pages
- [x] Add listings section for ERC1155 tokens

Designs:
https://www.figma.com/file/viovJLYOfUuB6TnW67qF5N/reservoir?node-id=0%3A1

**Comment by diegoramosxyz** [comment]
@rorygeoghegan I'm missing the LooksRare and OpenSea icons. I think it's not ideal to export them from Figma. The should instead be provided in the ticket.

**Comment by rorygeoghegan** [comment]
![looksrare-green](https://user-images.githubusercontent.com/96800113/164282304-d637e88a-d5f1-4d32-ba50-99d56be06303.svg)
![opensea-blue](https://user-images.githubusercontent.com/96800113/164282306-d2760d61-30c0-4a18-bf0d-aa15c6322c1e.svg)

**Comment by diegoramosxyz** [comment]
I got the LooksRare logo from Lingzi and it looks different. I used her's because it matches Figma.

@rorygeoghegan This endpoint doesn't return the total owners or the supply count. 

https://api-rinkeby.reservoir.tools/tokens/details/v3?tokens=0xfb8695dc919078c37fe507b800e2c33ed3d815d8:1

Where should I get these values from?

**Comment by diegoramosxyz** [comment]
@rorygeoghegan I don't know where to get the data to create the listings table for the ERC1155 token page.

The `/details` endpoint does not include it:

https://api-rinkeby.reservoir.tools/tokens/details/v3?tokens=0xfb8695dc919078c37fe507b800e2c33ed3d815d8:1

**Comment by rorygeoghegan** [comment]
> @rorygeoghegan This endpoint doesn't return the total owners or the supply count for ERC1155 tokens.

We discussed this one this morning. Just keep it the same for ERC1155 and 721 for now and we'll block this task until we can get it supported from backend.

**Comment by rorygeoghegan** [comment]
> @rorygeoghegan I don't know where to get the data to create the listings table for the ERC1155 token page.

You can find this in the asks api:
https://api.reservoir.tools/orders/asks/v1?token=0x22c36bfdcef207f9c0cc941936eff94d4246d14a%3A0&limit=50
