### ISSUE TITLE
Research: Support connecting wallet on mobile browser

### ISSUE THREAD

**Issue by rorygeoghegan** [reservoirprotocol/sample-marketplace#198]

**Comment by diegoramosxyz** [comment]
@rorygeoghegan Currently the sample marketplace supports mobile devices, but only on web3 browsers/apps. For example, you can download MetaMask and use its browser to connect your wallet. This is how it works on desktop. When you get a browser extension that injects an object on every page which enables all Ethereum functions.

Have you seen another form to connect you wallet on a browser like Safari on iOS. As far as I know, that's not currently possible. Safari can't be used to interact with Ethereum.

**Comment by rorygeoghegan** [comment]
There's no native browser support that I'm aware but this task is more about improving the UX. Currently when I click connect wallet on mobile nothing happens. At the very least we should be linking you to install the metamask app if not already installed or deeplink you to their dapp browser if it is installed. We should also add support for wallet connect.

OpenSea is a good example of how this should work.
