### ISSUE TITLE
Add source icon (opensea/looksrare) to token cards on collection page

### ISSUE THREAD

**Issue by rorygeoghegan** [reservoirprotocol/sample-marketplace#199]
Design:
https://www.figma.com/file/viovJLYOfUuB6TnW67qF5N/reservoir?node-id=0%3A1

Source can be any reservoir powered marketplace (eg Forgotten Market, Reservoir Market) or aggregated marketplace (eg LooksRare or OpenSea)

**Comment by diegoramosxyz** [comment]
@rorygeoghegan I can't complete this task with the data returned by this endpoint: https://api-rinkeby.reservoir.tools/tokens/v2?limit=20&collection=0xb74bf94049d2c01f8805b8b15db0909168cabf46&sortBy=floorAskPrice

I need either the source on each token object, or the backend needs to be modified to accept the token with format: `{contract-address}:{tokenId}` as the source.

I'm using `redirect/logo/v1` to complete this task. https://api.reservoir.tools/#/5.%20Redirects/getRedirectLogoV1

**Comment by rorygeoghegan** [comment]
@diegoramosxyz Use v4 for this api and you'll get the source

Example:
https://api-rinkeby.reservoir.tools/tokens/v4?limit=20&collection=0xb74bf94049d2c01f8805b8b15db0909168cabf46&sortBy=floorAskPrice
