### ISSUE TITLE
Disable body parser for analytics forwarder

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/sample-marketplace#205]
The datadog team suspect that the reason session recordings don't work is that the body is being transformed by next.js:

https://nextjs.org/docs/api-routes/api-middlewares#custom-config

I tried turning it off, but got errors, so need Diego to have a try.

**Comment by ptrwtts** [comment]
Ideally we prioritize this, to see if it can fix session recording

**Comment by diegoramosxyz** [comment]
@ptrwtts How do I test this? It's live on `dev`.

**Comment by ptrwtts** [comment]
Do requests through to Datadog work? Can look in the network requests
