### ISSUE TITLE
Support setting a fee

### ISSUE THREAD

**Issue by rorygeoghegan** [reservoirprotocol/sample-marketplace#211]
It should be possible to set a fee via two ENV variables:

- FEE_BPS
- FEE_RECIPIENT

As part of this, we should use 0x exchange for single token orders (not attribute / collection orders)

**Comment by rorygeoghegan** [comment]
Add marketplace fees to listing and offer module
- [ ] Add "[marketplace name] x%" Eg "Reservoir Market 1%" below Royalty x% on  Listing module
- [ ] Add "[marketplace name] x%" Eg "Reservoir Market 1%" below Royalty x% on  Single token offer module

@diegoramosxyz let's chat before you pick up this ticket so we can discuss how it should work

**Comment by diegoramosxyz** [comment]
@rorygeoghegan I need help integrating the BPS fee coming from the environment variables into the calculation for the final price: https://github.com/reservoirprotocol/sample-marketplace/blob/dev/lib/calculateOffer.ts
