### ISSUE TITLE
Collection stats and attribute filter stats

### ISSUE THREAD

**Issue by rorygeoghegan** [reservoirprotocol/sample-marketplace#218]
On the collection page we currently update the stats displayed under the collection title as a user filters through attributes.

We want to update this so that the top level stats don't update as the user filters. Instead we will add an additional stats section above the tokens grid that reflects the current filtered state.

- [x] Update collection stats so that they don't update as user filters attributes
![Screen Shot 2022-04-28 at 1 17 16 PM](https://user-images.githubusercontent.com/96800113/165954035-1fbf0628-dc3d-4b7f-bd30-eabeaed21fae.png)

- [x] Add new attribute stats above tokens grid that update as a user filters attributes. These stats include items within current filter and floor price of current filter
![Screen Shot 2022-04-28 at 1 17 22 PM](https://user-images.githubusercontent.com/96800113/165954201-0115a28d-2662-461a-aadb-3bcccaad8b53.png)
![Screen Shot 2022-04-29 at 9 32 50 AM](https://user-images.githubusercontent.com/96800113/165954631-829bb3c4-8238-4f48-b206-e833781f40d5.png)

Figma designs:
https://www.figma.com/file/viovJLYOfUuB6TnW67qF5N/reservoir?node-id=0%3A1
https://www.figma.com/file/viovJLYOfUuB6TnW67qF5N/reservoir?node-id=655%3A12009

**Comment by diegoramosxyz** [comment]
@rorygeoghegan How do I calculate the floor change percentage? 

How do I calculate the volume change percentage? The API returns volume change in this format: 0.1941747572815534

What does it represent?

**Comment by diegoramosxyz** [comment]
@rorygeoghegan I see this is another ticket. Never mind.

**Comment by rorygeoghegan** [comment]
- [ ] Light mode colors appearing on darkmode (please check UI updates on both modes)
<img width="351" alt="Screen Shot 2022-05-07 at 9 51 09 AM" src="https://user-images.githubusercontent.com/96800113/167257305-86969728-23bf-4036-a2d4-84f134a2cf48.png">
- [ ] Drop down menu starts on left side while waiting for filter data then switches to right. It should just start on the right side (see video)
https://www.loom.com/share/e8c7648a48274d6e86aa63f93016131e

**Comment by rorygeoghegan** [comment]
- [ ] Add comma , in item count (ie. 10000 should be 10,000)
<img width="394" alt="Screen Shot 2022-05-10 at 12 51 38 PM" src="https://user-images.githubuserconten
- [ ] Tag darkmode color is incorrect when filtering to attribute key
<img width="437" alt="Screen Shot 2022-05-10 at 12 51 46 PM" src="https://user-images.githubusercontent.com/96800113/167685167-1bd11343-01dc-4d06-ace3-fbf7a99ebc7a.png">
t.com/96800113/167685099-3bda95bd-d1b2-488d-8f36-67a5c8bf440f.png">

**Comment by rorygeoghegan** [comment]
Ready for staging
