### ISSUE TITLE
Add 24 hour volume and % change on collection page

### ISSUE THREAD

**Issue by rorygeoghegan** [reservoirprotocol/sample-marketplace#219]
- [ ] Using collections/v3 api display 1day volume for each collection
- [ ] Using collections/v3 api display 1day volume change for each collection

Example
If volumechange = 1.1234 then percentage change is +12.34%
If volumechange = 0.4321 then percentage change is -56.79%

![Screen Shot 2022-04-29 at 9 35 50 AM](https://user-images.githubusercontent.com/96800113/165960435-445606a4-d952-43ca-8343-55acb8c5745e.png)
![Screen Shot 2022-04-29 at 9 35 37 AM](https://user-images.githubusercontent.com/96800113/165960437-c234929f-93a0-47a6-9ea7-b4f9b5b942c9.png)

Figma designs:
https://www.figma.com/file/viovJLYOfUuB6TnW67qF5N/reservoir?node-id=0%3A1

**Comment by diegoramosxyz** [comment]
@rorygeoghegan `/collection/v1`, which we already use returns the volume data. Are you sure you want to  add another api call to `collections/v3` to get the same data?

**Comment by rorygeoghegan** [comment]
**Collection Stats Number Formatting**

- [ ] **Percentages**
% change numbers only show max 2 decimal place
If % change is positive add + symbol and use green text
If % change is negative add - symbol and use red text

- [ ] **ETH Volume**
0-999 ETH show max 2 decimal places
1,000+ ETH abbreviate to use 1K format with max 2 decimal place (eg 12,345 ETH = 12.34K ETH) 

- [ ] **Item Counts**
Add , to numbers over 1,000 (eg. 10000 items = 10,000 items)
Always display full number for item counts

**Comment by rorygeoghegan** [comment]
- [ ] Add '+' symbol for when the % change is positive
- [ ] Remove duplicate Item count

**Comment by rorygeoghegan** [comment]
Ready for staging
