### ISSUE TITLE
Improve wallet connect flow

### ISSUE THREAD

**Issue by rorygeoghegan** [reservoirprotocol/sample-marketplace#221]
Currently our connect wallet flow only supports metamask and is lacking any instructions for newer users. We also do not support deeplinking to a users preferred wallet browser on mobile. By improving this UX we can also improve the trust of the platform.

- [ ] When user clicks on Connect Wallet button or attempts to make an action that requests a connected wallet (eg. Buy, Bid, List etc) we prompt them with the connect wallet module
![Screen Shot 2022-04-29 at 10 23 02 AM](https://user-images.githubusercontent.com/96800113/165963503-27e3fdaa-aa1b-4408-971a-012cc310ea6d.png)
![Screen Shot 2022-04-29 at 10 22 55 AM](https://user-images.githubusercontent.com/96800113/165963505-7402ad11-26c4-467d-8c69-2cfeeee8ca86.png)

Desktop

- [x] If user clicks metamask and does not have it installed then open new tab to https://metamask.io/download/
- [x] If user clicks metamask and does have it installed then open metamask extension
- [x] If user clicks wallet connect then follow their guide https://docs.walletconnect.com/quick-start/dapps/client
- [x] If user clicks coinbase then follow their guide https://docs.cloud.coinbase.com/wallet-sdk/docs/installing

Mobile
- [ ] If user clicks metamask and does not have it installed then deeplink them to the metamask appstore/playstore page to download
- [ ] If user clicks metamask and does have it installed then deeplink to metamask app and open the current url they are on in the app browser (https://docs.metamask.io/guide/mobile-best-practices.html#using-walletconnect)
- [x] If user clicks wallet connect then follow their guide https://docs.walletconnect.com/mobile-linking
- [x] If user clicks coinbase then follow their guide https://docs.cloud.coinbase.com/wallet-sdk/docs/deep-link-into-dapp-browser

Figma designs:
https://www.figma.com/file/viovJLYOfUuB6TnW67qF5N/reservoir?node-id=0%3A1

**Comment by diegoramosxyz** [comment]
@lingzizheng please, provide the MetaMask, WalletConnect and Coinbase logos to be used in the modal.

**Comment by lingzizheng** [comment]
![walletconnect-circle-white 1](https://user-images.githubusercontent.com/33438546/166563970-85776929-1de7-4a68-aae8-1a23eec77cec.svg)
![metamask-fox 1](https://user-images.githubusercontent.com/33438546/166563972-628509de-e1fe-4654-b52d-1ff6e798e16d.svg)
![Coinbase-icon-symbol-1](https://user-images.githubusercontent.com/33438546/166564953-1d24af32-106e-425d-9ec6-20c461d82d9f.svg)

**Comment by lingzizheng** [comment]
![Coinbase-wallet-icon-symbol-1 1](https://user-images.githubusercontent.com/33438546/166566002-dd5f99d1-88af-499a-a65f-e730b9044af1.svg)
![metamask-fox 1](https://user-images.githubusercontent.com/33438546/166566003-203d4257-88cf-488b-a77b-bfe9066234e4.svg)
![walletconnect-circle-white 1](https://user-images.githubusercontent.com/33438546/166566005-589f9e78-659a-42dc-b955-764d6b33cf21.svg)

**Comment by rorygeoghegan** [comment]
Remaining tasks:

- [ ] Drop down menu automatically opens after connecting
- [ ] Cannot close drop down menu by closing outside of it
- [ ] Add Connect Wallet UX to router demo
- [ ] Arrow/Chevron icons not matching design - They look much smaller
