### ISSUE TITLE
Bug: Dark mode - ETH Token Color is wrong 

### ISSUE THREAD

**Issue by lingzizheng** [reservoirprotocol/sample-marketplace#244]
<img width="124" alt="Screen Shot 2022-05-03 at 11 29 27 AM" src="https://user-images.githubusercontent.com/33438546/166484917-1755dedd-258b-478a-bdff-5c35b944524e.png">

Use this dark mode purple ETH icon for dark mode.
![Ethereum-icon-purple](https://user-images.githubusercontent.com/33438546/166505268-8a7e1419-994a-4f84-aee7-596e598a2a1b.svg)

**Comment by diegoramosxyz** [comment]
@lingzizheng I need both icons to have the same dimensions. The dark mode eth icon is smaller after setting its width.

**Comment by lingzizheng** [comment]
Done!
