### ISSUE TITLE
Bug: Dark mode - Selected state color is wrong 

### ISSUE THREAD

**Issue by lingzizheng** [reservoirprotocol/sample-marketplace#247]
<img width="419" alt="Screen Shot 2022-05-03 at 12 01 35 PM" src="https://user-images.githubusercontent.com/33438546/166490780-7c89e378-155f-41ef-9bcf-18c9699cc01f.png">

Selected state will use the same color as hover state, which is solid/900 #430099

**Comment by rorygeoghegan** [comment]
Duplicate
