### ISSUE TITLE
Add support for Druk Text Wide Web

### ISSUE THREAD

**Issue by rorygeoghegan** [reservoirprotocol/sample-marketplace#250]
1. Change the sidebar font from H6 to Label/L. 
![Image](https://user-images.githubusercontent.com/33438546/166811532-6d8aad85-e61a-4033-a64e-24e8f9c8c855.png)

2. Change the sort by drop down text from H6 to Label/L.
![Image](https://user-images.githubusercontent.com/33438546/166811605-04c044b3-ca18-4d0f-b009-0e8bc6cc6ae5.png)

3. Update all the fonts from H1-H6 to using Druk Text Wide Web font face while maintaining the same font size, in theory, it shouldn't break anything.

**Comment by diegoramosxyz** [comment]
@lingzizheng Do you have the Durk font files? I would I add it in this folder: https://github.com/reservoirprotocol/sample-marketplace/tree/main/public/fonts

**Comment by rorygeoghegan** [comment]
@diegoramosxyz So far we don't plan to fork unless we really need to so let's include keep this on sample marketplace repo.

**Comment by lingzizheng** [comment]
[Druk Text Wide Web Medium Regular.zip](https://github.com/reservoirprotocol/sample-marketplace/files/8641787/Druk.Text.Wide.Web.Medium.Regular.zip)

**Comment by lingzizheng** [comment]
They only use the medium regular for this font

**Comment by rorygeoghegan** [comment]
- [ ] Custom texts should only be applied to headings (H1-H6) all other styles should remain as inter.

**Comment by rorygeoghegan** [comment]
- [ ] Collection stats should be Headings/Subtitle style not h6 (see designs)

**Comment by rorygeoghegan** [comment]
Ready for staging
