### ISSUE TITLE
Site logo should match the domain/sub-domain

### ISSUE THREAD

**Issue by rorygeoghegan** [reservoirprotocol/sample-marketplace#36]
For example:
For general marketplace use reservoir.market logo (reservoir.market)
For Bored Apes Yacht Club use Bored Apes Yacht Club logo (boredapesyachtclub.reservoir.market)
For Bored Apes Community use BAYC logo (bayc.reservoir.market)

**Comment by diegoramosxyz** [comment]
@rorygeoghegan for `{communityId}.reservoir.market/collections/{collectionId}` having a the BAYC logo on the navbar would require removing `getStaticProps` making the user experience slower for navigating between collections within the community. Do you want me to make that change nonetheless? 

The rest of the cases have the logo now.
