### ISSUE TITLE
Add datadog analytics to sample marketplaces

### ISSUE THREAD

**Issue by rorygeoghegan** [reservoirprotocol/sample-marketplace#45]

**Comment by ptrwtts** [comment]
Important to remember that this is a template to fork. Not everyone will be using Datadog. So two points:

- It should work perfectly without the Datadog ENV variables being set
- Let's call the hook something more generic, like `useAnalytics`. Within the file, there will be an implementation of Datadog, but we can also have a comment saying "Add your own analytics implementation here", and maybe at some point we could add other implementations for people like Google Analytics.

**Comment by diegoramosxyz** [comment]
@ptrwtts I'm not familiar enough with analytics to create a replaceable function for analytics. For example, we have a proxy and require the user's Ethereum address if they are connected. Is it enough to add "Add your own analytics implementation here" on this function? https://github.com/reservoirprotocol/sample-marketplace/blob/main/hooks/useAnalytics.ts
