### ISSUE TITLE
BUG: Buy now button on collection page doesn't work

### ISSUE THREAD

**Issue by rorygeoghegan** [reservoirprotocol/sample-marketplace#47]
When I click this button, nothing happens.

**Comment by diegoramosxyz** [comment]
@georgeroman This endpoint is supposed to return token data for the floor: https://rinkeby-api-v4.reservoir.tools/stats?collection=forgottenruneswizardscult

https://mainnet-api-v4.reservoir.tools/documentation#/stats/getStats

This is causing this error. Should I rely on this endpoint for this function?

**Comment by georgeroman** [comment]
@diegoramosxyz What do you mean by "return token data for the floor"? Does the response miss anything that it previously returned in an old version?

**Comment by diegoramosxyz** [comment]
@georgeroman This is what [the docs](https://mainnet-api-v4.reservoir.tools/documentation#/stats/getStats) say the response from this endpoint should be: 

```json
{
  "stats": {
    "tokenCount": 0,
    "onSaleCount": 0,
    "sampleImages": [
      "string"
    ],
    "lastBuy": {
      "value": 0,
      "block": 0
    },
    "market": {
      "floorSell": {
        "hash": "string",
        "value": 0,
        "maker": "string",
        "validFrom": 0,
        "validUntil": 0,
        "token": {
          "contract": "string",
          "tokenId": "string",
          "name": "string",
          "image": "string"
        }
      },
      "topBuy": {
        "hash": "string",
        "value": 0,
        "maker": "string",
        "validFrom": 0,
        "validUntil": 0
      }
    }
  }
}
```

On the example call I provided: https://rinkeby-api-v4.reservoir.tools/stats?collection=forgottenruneswizardscult

```json
"token": {
          "contract": "string",
          "tokenId": "string",
          "name": "string",
          "image": "string"
        }
```

is missing. I need that token object to have a `buy now` button that updates based on filtering.

**Comment by georgeroman** [comment]
Will add that today
