### ISSUE TITLE
BUG: Incorrect total being calculated 

### ISSUE THREAD

**Issue by rorygeoghegan** [reservoirprotocol/sample-marketplace#49]
1. I make an offer for 0.01 ETH
<img width="414" alt="Screen Shot 2022-02-02 at 6 49 13 PM" src="https://user-images.githubusercontent.com/96800113/152257927-10929bc1-63c1-467f-81bf-cb83564cfa11.png">

Expected:
Total cost with royalty should be 0.011 and displayed offer should be 0.01

Actual:
Top offer is appearing as 0.0099
<img width="213" alt="Screen Shot 2022-02-02 at 6 49 32 PM" src="https://user-images.githubusercontent.com/96800113/152258028-674767af-8df0-4fea-ab89-f6d9bb9dd404.png">

**Comment by rorygeoghegan** [comment]
The issue here is how you are calculating the total amount(offer + royalty).

Instead of 0.01 + (0.01 * 0.1)
it should be 0.01 / 1.1

**Comment by diegoramosxyz** [comment]
@rorygeoghegan I'm confused. This value should be correct when coming from the API. When I'm creating the order I pass that calculated value of `0.011`. @georgeroman Are we supposed to display a value that is higher the one returned in the API? See this example:

https://mainnet-api-v4.reservoir.tools/tokens?attributes[Shirt]=swat&limit=20&offset=0&collection=crazy-babies-official&sortBy=floorSellValue&sortDirection=asc

Here's how I'm calculating the total cost: 

https://github.com/reservoirprotocol/sample-marketplace/blob/dev/lib/calculateOffer.ts#L17-L18

Which is `input + ((input * bps)/10000)`

**Comment by georgeroman** [comment]
@diegoramosxyz This is how the value is computed on the backend: https://github.com/reservoirprotocol/indexer-v3/blob/169687750ce5a4972434be3e3c4ea1e6ebe8e7e7/src/orders/wyvern-v2/save.ts#L525-L532.

**Comment by diegoramosxyz** [comment]
@ptrwtts @rorygeoghegan I think the issue is caused by using javascript numbers instead of BigNumbers at the API level. Somewhere in the conversions between BigNumber and number we are losing precision. I believe on my end, the calculations are correct. [See equation](https://github.com/reservoirprotocol/sample-marketplace/blob/dev/lib/calculateOffer.ts#L17-L18).

**Comment by ptrwtts** [comment]
Change this
```
let fee = userInput.mul(BigNumber.from(bps)).div(BigNumber.from('10000'))
let total = userInput.add(fee)
```
to 
```
let feePercent = BigNumber.from(bps).div(BigNumber.from('10000'))
let total = userInput.div( BigNumber.from('1').minus(feePercent) )
```

**Comment by diegoramosxyz** [comment]
Fixed here: https://github.com/reservoirprotocol/sample-marketplace/commit/099688c6c751d3d3d8ee3ca2b50b12a35d1facde
