### ISSUE TITLE
Set logo and name via env variable

### ISSUE THREAD

**Issue by rorygeoghegan** [reservoirprotocol/sample-marketplace#63]
- [x] Default logo and name will be reservoir.market for all marketplaces
- [x] Developer can set their own logo and name via the env variable

**Comment by diegoramosxyz** [comment]
The developer can set `NEXT_PUBLIC_NAVBAR_TITLE` and `NEXT_PUBLIC_NAVBAR_LOGO` to set the title and logo in the navbar.
